#spring:
#  jpa:
#    database: POSTGRESQL
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#  datasource:
#    url: jdbc:postgresql://localhost:5432/fmanager?useUnicode=true
#    username: fmanager_user
#    password: root
#    driver-class-name: org.postgresql.Driver
#    initialization-mode: always

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/test
    initialization-mode: always

#    localhost:8080/h2-console  <- http address to manage db